package com.anchibaby.mtzimporter;

import android.app.Activity;
import android.app.AlertDialog;
import android.content.ComponentName;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.View;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ProgressBar;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Method;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import rikka.shizuku.Shizuku;

public class MainActivity extends Activity {
 private static final int PICK=1001, SHI=1002, APPLY=2001; private final ExecutorService ex=Executors.newSingleThreadExecutor();
 private TextView log,picked,pt; private ProgressBar pb; private Button go; private File mtz; private volatile boolean ready,running; private String officialTemp,officialBackup,beforeState;
 private final Shizuku.OnBinderReceivedListener br=()->runOnUiThread(()->{ready=true; add("✓ Shizuku Binder 已連線"); prog(10,"Shizuku 就緒");});
 private final Shizuku.OnBinderDeadListener bd=()->runOnUiThread(()->{ready=false;add("! Shizuku 已中斷");prog(0,"Shizuku 中斷");});
 private final Shizuku.OnRequestPermissionResultListener pr=(r,g)->{if(r==SHI) runOnUiThread(()->add(g==PackageManager.PERMISSION_GRANTED?"✓ Shizuku 已授權":"✗ Shizuku 未授權"));};
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());add("版本：0.12.0 persistent registry diff");add("持久保存套用前快照，並唯讀檢查 description.xml、package.xml 與 MediaStore 登錄線索。");Shizuku.addBinderReceivedListenerSticky(br);Shizuku.addBinderDeadListener(bd);Shizuku.addRequestPermissionResultListener(pr);state();}
 @Override protected void onDestroy(){Shizuku.removeBinderReceivedListener(br);Shizuku.removeBinderDeadListener(bd);Shizuku.removeRequestPermissionResultListener(pr);ex.shutdownNow();super.onDestroy();}
 private View ui(){int p=dp(18);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(p,p,p,p);TextView t=new TextView(this);t.setText("MTZ 登錄差異診斷 v0.12");t.setTextSize(23);r.addView(t);TextView d=new TextView(this);d.setText("持久保存套用前快照，並唯讀檢查主題描述與登錄線索。");d.setPadding(0,dp(6),0,dp(10));r.addView(d);pt=new TextView(this);pt.setText("0% · 待命");r.addView(pt);pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);r.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));r.addView(btn("1. 檢查 / 授權 Shizuku",v->auth()));r.addView(btn("2. 選擇 MTZ",v->choose()));picked=new TextView(this);picked.setText("尚未選擇 MTZ");picked.setPadding(0,dp(6),0,dp(6));r.addView(picked);r.addView(btn("3. 交給官方解析並套用",v->officialApply()));r.addView(btn("開啟官方本機／自訂主題頁",v->probeOfficial()));r.addView(btn("清除執行紀錄",v->{log.setText("");prog(0,"待命");}));TextView h=new TextView(this);h.setText("\n執行紀錄（可長按複製）");h.setTextSize(18);r.addView(h);log=new TextView(this);log.setTextIsSelectable(true);log.setTextSize(12);ScrollView sv=new ScrollView(this);sv.addView(log);r.addView(sv,new LinearLayout.LayoutParams(-1,0,1));return r;}
 private Button btn(String x,View.OnClickListener l){Button b=new Button(this);b.setText(x);b.setOnClickListener(l);return b;}
 private void state(){try{if(!Shizuku.pingBinder()){ready=false;add("! 等待 Shizuku Binder");return;}ready=true;if(Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED){add("✓ Shizuku Binder 正常且已授權");prog(10,"Shizuku 就緒");}else add("! Shizuku 已連線但尚未授權");}catch(Throwable t){add("✗ Shizuku："+err(t));}}
 private void auth(){try{if(!Shizuku.pingBinder()){state();return;}if(Shizuku.checkSelfPermission()==PackageManager.PERMISSION_GRANTED){add("✓ 已有 Shizuku 權限");return;}Shizuku.requestPermission(SHI);}catch(Throwable t){add("✗ "+err(t));}}
 private void choose(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
 @Override protected void onActivityResult(int q,int res,Intent data){super.onActivityResult(q,res,data);if(q==APPLY){finishOfficial(res,data);return;}if(q!=PICK||res!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();String n=name(u);if(n==null)n="selected.mtz";if(!n.toLowerCase().endsWith(".mtz")){Toast.makeText(this,"請選擇 .mtz",Toast.LENGTH_LONG).show();return;}String nn=safe(n);picked.setText("讀取中："+nn);prog(18,"讀取 MTZ");ex.execute(()->stage(u,nn));}
 private void officialApply(){if(mtz==null||!mtz.isFile()){add("✗ 請先選擇 MTZ");return;}if(!ok())return;new AlertDialog.Builder(this).setTitle("交給官方套用主題？").setMessage("系統外觀、圖示、鎖定畫面或桌布可能立即變更。之後可在個性主題中換回原本主題。").setNegativeButton("取消",null).setPositiveButton("繼續",(d,w)->prepareOfficial()).show();}
 private void prepareOfficial(){prog(30,"記錄套用前狀態");ex.execute(()->{beforeState=snapshot();saveBefore(beforeState);String path="/sdcard/Download/temp.mtz",backup="/sdcard/Download/temp.mtz.mtzimporter.bak";prog(40,"建立下載根目錄 temp.mtz");CommandResult c=cmd("rm -f "+q(backup)+"; if test -e "+q(path)+"; then mv "+q(path)+" "+q(backup)+"; fi; cp "+q(mtz.getAbsolutePath())+" "+q(path)+" && chmod 0644 "+q(path)+" && test -s "+q(path));if(c.code!=0){cmd("if test -e "+q(backup)+"; then mv "+q(backup)+" "+q(path)+"; fi");addW("✗ temp.mtz 準備失敗："+c.out);prog(0,"無法準備 MTZ");return;}officialTemp=path;officialBackup=backup;addW("✓ 已準備："+path);addW("若出現檔案選擇器，請直接點選下載根目錄的 temp.mtz。");runOnUiThread(()->launchOfficial(path));});}
 private void launchOfficial(String path){try{prog(60,"啟動小米官方解析器");Intent i=new Intent(Intent.ACTION_MAIN);i.setComponent(new ComponentName("com.android.thememanager","com.android.thememanager.ApplyThemeForScreenshot"));i.putExtra("theme_file_path",path);i.putExtra("theme_apply_flags",-1L);i.putExtra("theme_remove_flags",0L);i.putExtra("api_called_from","ThemeStore-MTZ-Importer-v0.10");add("→ 已交給官方 ApplyThemeForScreenshot");startActivityForResult(i,APPLY);}catch(Throwable t){add("✗ 官方入口啟動失敗："+err(t));cleanupOfficial();prog(0,"啟動失敗");}}
 private void cleanupOfficial(){String path=officialTemp,backup=officialBackup;officialTemp=null;officialBackup=null;if(path==null)return;ex.execute(()->{CommandResult c=cmd("rm -f "+q(path)+"; if test -e "+q(backup)+"; then mv "+q(backup)+" "+q(path)+"; fi");addW(c.code==0?"✓ temp.mtz 已清理，原同名檔案已還原":"! temp.mtz 清理結果："+c.out);});}
 private void finishOfficial(int res,Intent data){String detail=bundleDetails(data==null?null:data.getExtras());add("官方回傳：resultCode="+res+(res==RESULT_OK?"（RESULT_OK）":"")+"\n"+detail);prog(85,"比較套用前後狀態");ex.execute(()->{String after=snapshot();if(beforeState==null)beforeState=loadBefore();addW("\n=== 套用前狀態 ===\n"+beforeState+"\n=== 套用後狀態 ===\n"+after);cleanupOfficial();prog(res==RESULT_OK?100:0,res==RESULT_OK?"官方套用完成；差異已記錄":"官方取消或套用失敗");});}
 private String bundleDetails(Bundle b){if(b==null)return"(無回傳 Bundle)";StringBuilder s=new StringBuilder("回傳 Bundle：");try{b.setClassLoader(getClassLoader());for(String k:b.keySet()){Object v;try{v=b.get(k);}catch(Throwable t){v="<無法讀取："+err(t)+">";}s.append("\n- ").append(k).append(" [").append(v==null?"null":v.getClass().getName()).append("] = ").append(String.valueOf(v));}}catch(Throwable t){s.append("\n<展開失敗：").append(err(t)).append('>');}return s.toString();}
 private String snapshot(){String q="echo '[theme metadata]'; for f in /data/system/theme/description.xml /data/system/theme/package.xml /data/system/theme/plugin_config.xml; do echo ---$f; sed -n '1,160p' $f 2>/dev/null; done; echo '[theme directory]'; ls -lnR /data/system/theme 2>/dev/null; echo '[MediaStore temp.mtz]'; content query --uri content://media/external/file --projection _id:_data:_display_name:owner_package_name 2>/dev/null | grep -F temp.mtz | head -n 20; echo '[settings]'; settings list system 2>/dev/null | grep -i -E 'theme|wallpaper|font'; settings list secure 2>/dev/null | grep -i -E 'theme|wallpaper|font'; echo '[properties]'; getprop | grep -i -E 'theme|wallpaper' | head -n 80";CommandResult r=cmd(q);return r.out.isEmpty()?"(無可讀狀態)":r.out;}
 private void saveBefore(String s){try(FileOutputStream f=new FileOutputStream(new File(getFilesDir(),"before_snapshot.txt"))){f.write((s==null?"(null)":s).getBytes("UTF-8"));}catch(Throwable t){addW("! 快照保存失敗："+err(t));}}
 private String loadBefore(){File x=new File(getFilesDir(),"before_snapshot.txt");if(!x.isFile())return"(找不到持久快照)";try(FileInputStream f=new FileInputStream(x)){byte[] b=new byte[(int)Math.min(x.length(),200000)];int n=f.read(b);return n<0?"(空快照)":new String(b,0,n,"UTF-8");}catch(Throwable t){return"(快照讀取失敗："+err(t)+")";}}
 private void stage(Uri u,String n){try{File dir=new File(getExternalFilesDir(null),"stage");dir.mkdirs();File o=new File(dir,System.currentTimeMillis()+"_"+n);long total=0;try(InputStream in=getContentResolver().openInputStream(u);FileOutputStream f=new FileOutputStream(o)){if(in==null)throw new Exception("無法開啟檔案");byte[] b=new byte[131072];int z;while((z=in.read(b))>=0){f.write(b,0,z);total+=z;}}if(total<64)throw new Exception("MTZ 太小");mtz=o;long sz=total;runOnUiThread(()->picked.setText("已選擇："+n+"\n"+sz+" bytes"));addW("✓ MTZ 已就緒");prog(25,"MTZ 已就緒");}catch(Throwable t){addW("✗ MTZ："+err(t));prog(0,"MTZ 讀取失敗");}}
 private void diagnoseOnly(){if(!ok())return;ex.execute(()->{prog(15,"辨識官方套件");String d=diagnostics();addW(d);prog(100,"診斷完成");});}
 private void scanRegistry(){if(!ok())return;if(running)return;running=true;ex.execute(()->{try{addW("\n=== 本機主題登錄精簡唯讀掃描 v0.8 ===");String[] qs={"find /sdcard/MIUI/theme -maxdepth 5 -type f 2>/dev/null | head -n 40","find /sdcard/Android/data/com.android.thememanager/files -type f 2>/dev/null | grep -v -E '/(adopt|frame|wallpaper|videowallpaper|cache)/' | grep -i -E '\\.(mtz|db|sqlite|json|xml)$|theme|meta|resource' | head -n 60","ls -la /data/system/theme 2>&1; find /data/system/theme -maxdepth 3 -type f 2>/dev/null | head -n 60","dumpsys package com.android.thememanager | grep -A 100 -B 5 'Providers:' | head -n 140","dumpsys package com.android.thememanager | grep -i -E 'provider|authority|database|content://' | head -n 100","cmd package query-activities --brief -a android.intent.action.VIEW -d theme://zhuti.xiaomi.com/customize -p com.android.thememanager","cmd package query-activities --brief -a android.intent.action.VIEW -d ViewLocalResource://view.local.resource/test -p com.android.thememanager"};String[] names={"/sdcard/MIUI/theme","過濾後 Theme Manager files","/data/system/theme","Provider 宣告","Authority／資料庫線索","官方 customize URI","ViewLocalResource 測試 URI"};for(int i=0;i<qs.length;i++){prog(10+i*12,"掃描 "+names[i]);CommandResult x=cmd(qs[i]);addW("\n[唯讀掃描 "+(i+1)+"] "+names[i]+" · exit="+x.code+"\n"+(x.out.isEmpty()?"(無結果或目錄不存在)":x.out));}prog(100,"唯讀掃描完成");addW("\n✓ 精簡掃描完成；請長按複製整段紀錄傳回。沒有寫入或刪除任何官方資料。");}catch(Throwable t){addW("✗ "+err(t));prog(0,"掃描失敗");}finally{running=false;}});}
 private String diagnostics(){StringBuilder s=new StringBuilder();String[] qs={"dumpsys package com.android.thememanager | grep -E 'versionName=|versionCode=' | head -n 2","cmd package resolve-activity --brief -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -p com.android.thememanager","dumpsys package com.android.thememanager | grep -A 24 -B 6 'mine.local.customize.ComponentActivity' | head -n 80","dumpsys package com.android.thememanager | grep -A 24 -B 6 'activity.ThemeDetailActivity' | head -n 100","cmd package resolve-activity --brief -a android.intent.action.VIEW -d ViewLocalResource://view.local.resource -p com.android.thememanager","cmd package resolve-activity --brief -a android.intent.action.VIEW -t application/zip -p com.android.thememanager"};for(int i=0;i<qs.length;i++){CommandResult r=cmd(qs[i]);s.append("\n[診斷 ").append(i+1).append("] exit=").append(r.code).append("\n").append(r.out.isEmpty()?"(無結果)":r.out).append('\n');}return s.toString();}
 private void probeOfficial(){if(!ok())return;if(running)return;running=true;ex.execute(()->{try{addW("\n=== 官方本機主題頁測試開始 ===");prog(15,"確認精確元件");String[] tests={"am start -W -n com.android.thememanager/.mine.local.customize.ComponentActivity","am start -W -a android.intent.action.VIEW -n com.android.thememanager/.mine.local.customize.ComponentActivity -d ViewLocalResource://view.local.resource/customize","am start -W -n com.android.thememanager/.ThemeResourceTabActivity","am start -W -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -p com.android.thememanager"};String[] names={"本機自訂 ComponentActivity（精確路徑）","ViewLocalResource + /customize","ThemeResourceTabActivity","官方 Launcher"};boolean success=false;for(int i=0;i<tests.length;i++){prog(25+i*18,"測試 "+names[i]);CommandResult x=cmd(tests[i]);addW("\n[接手測試 "+(i+1)+"] "+names[i]+"\nexit="+x.code+"\n"+x.out);if(x.code==0&&(x.out.contains("Status: ok")||x.out.contains("Activity:"))){success=true;addW("✓ Android 回報官方已接手："+names[i]);break;}Thread.sleep(350);}if(!success){addW(diagnostics());addW("✗ 精確元件仍無法啟動，請把這段紀錄傳回。");}prog(100,success?"官方本機主題頁已接手":"精確入口仍被系統拒絕");}catch(Throwable t){addW("✗ "+err(t));prog(0,"測試失敗");}finally{running=false;}});}
 private void start(){if(running)return;if(mtz==null||!mtz.isFile()){add("✗ 請先選 MTZ");return;}if(!ok())return;running=true;runOnUiThread(()->go.setEnabled(false));ex.execute(()->{String dir="/sdcard/Android/data/com.android.thememanager/files/MIUI/theme/.data/import/theme", target=dir+"/chatgpt_"+System.currentTimeMillis()+"_"+safe(mtz.getName());try{prog(32,"診斷官方 Import 入口");String dg=diagnostics();addW(dg);prog(48,"寫入 Import staging");CommandResult cp=cmd("mkdir -p "+q(dir)+" && cp "+q(mtz.getAbsolutePath())+" "+q(target)+" && chmod 0644 "+q(target)+" && test -s "+q(target));if(cp.code!=0){addW("✗ staging 寫入失敗："+cp.out);prog(0,"寫入失敗");return;}addW("✓ staging 寫入成功："+target);prog(62,"測試官方可解析 VIEW 入口");CommandResult mime=cmd("cmd package resolve-activity --brief -a android.intent.action.VIEW -t application/zip -p com.android.thememanager");boolean has=mime.code==0&&mime.out.contains("com.android.thememanager/");if(has){addW("✓ 找到可解析 VIEW Activity："+mime.out);prog(72,"嘗試交給官方 VIEW 入口");CommandResult v=cmd("am start -W -a android.intent.action.VIEW -t application/zip -d file://"+qPath(target)+" -p com.android.thememanager");addW("VIEW exit="+v.code+"\n"+v.out);}else{addW("! Theme Manager 沒有公開可解析的 MTZ/ZIP VIEW Activity。這表示單純 Shizuku 複製不能啟動內部 ThemeImportManager。");}prog(84,"確認 staging 是否被接手");Thread.sleep(2500);CommandResult e=cmd("test -e "+q(target));if(e.code!=0){addW("✓ staging 已被 Theme Manager 移走，Import 有反應");prog(100,"Theme Manager 已接手");}else{addW("✗ staging 仍存在：官方沒有接受這個 MTZ。為避免殘留，現在清除測試檔。");cmd("rm -f "+q(target));prog(100,"官方 Import 未接受 · 已安全清理");}}catch(Throwable t){addW("✗ "+err(t));prog(0,"執行失敗");}finally{running=false;runOnUiThread(()->go.setEnabled(true));}});}
 private boolean ok(){try{if(!ready||!Shizuku.pingBinder()||Shizuku.checkSelfPermission()!=PackageManager.PERMISSION_GRANTED){add("✗ Shizuku 尚未就緒");auth();return false;}return true;}catch(Throwable t){add("✗ "+err(t));return false;}}
 private CommandResult cmd(String c){StringBuilder o=new StringBuilder();int ec=-1;try{Method m=Shizuku.class.getDeclaredMethod("newProcess",String[].class,String[].class,String.class);m.setAccessible(true);Process p=(Process)m.invoke(null,new Object[]{new String[]{"sh","-c",c},null,null});try(BufferedReader a=new BufferedReader(new InputStreamReader(p.getInputStream()));BufferedReader b=new BufferedReader(new InputStreamReader(p.getErrorStream()))){String l;while((l=a.readLine())!=null)o.append(l).append('\n');while((l=b.readLine())!=null)o.append(l).append('\n');}ec=p.waitFor();}catch(Throwable t){o.append(err(t));}return new CommandResult(ec,o.toString().trim());}
 private String name(Uri u){try(Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Throwable ignored){}return null;}
 private void prog(int n,String s){runOnUiThread(()->{pb.setProgress(Math.max(0,Math.min(100,n)));pt.setText(n+"% · "+s);});}private void add(String s){if(log!=null)log.append((log.length()==0?"":"\n")+s);}private void addW(String s){runOnUiThread(()->add(s));}private int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}private static String safe(String s){return s.replaceAll("[^a-zA-Z0-9._\\-\\u4e00-\\u9fff]","_");}private static String q(String s){return"'"+s.replace("'","'\\''")+"'";}private static String qPath(String s){return s.replace(" ","%20");}private static String err(Throwable t){return t.getClass().getSimpleName()+": "+String.valueOf(t.getMessage());}private static class CommandResult{final int code;final String out;CommandResult(int c,String o){code=c;out=o;}}
}
